#Pandas library

## Import library

in order to you use ay library first you need to import it.

In [1]:
import pandas as pd # alias pandas as pd
# import library name
# importing library will give me an acces to all feature in this library
# this library is only avaliable in this notebook.

##Manually creating DataFrame

In [2]:
# this is a dictionary
# using DataFrame,  we will convert dict to DataFrame
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40,45]
}

# this code: go to pandas library, use dataframe function and turn data dict into dataframe
pd.DataFrame(data)

   calories  duration
0       420        50
1       380        40
2       390        45

## Defining pd.DataFrame(data) as df to simplify

In [3]:
df = pd.DataFrame(data)
# this code will create a df variable

## Import file

In [4]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student.csv

In [5]:
df = pd.read_csv("student.csv") # read the csv file

##Exploring Data set

In [ ]:
df.head() # show top 5 rows

In [ ]:
# show 3 rows
df.head(3)

In [10]:
#show last 5 rows
df.tail()
df.tail(2) # show 2 rows

    id        name  class  mark  gender
33  34    Gain Toe  Seven    69    male
34  35  Rows Noump    Six    88  female

In [ ]:
df.count()

In [ ]:
# random sample data
df.sample()

In [14]:
df.shape # number of rows and columns

(35, 5)

In [ ]:
# dataset information
df.info()

In [ ]:
# statistical summary
df.describe()

std = standart deviation
25% = 1st quarter
50% = median values
75% = 3rd quarter
25% represnet: 25% of the students have mark equal to or less than 62.5
mean usually is higher than std. if std is close or higher than mean, there are outliers.

##Select sigle columns

In [ ]:
df["name"] #return names column

In [ ]:
df.name

## select multiple columns

In [ ]:
df[["name", "class", "mark"]]
# names and classes
# [] single bracket to pass 1 argumnet
## [[]] double to pass a list with multiple values

In [ ]:
df[["name", "class", "gender"]].head()

In [26]:
# select mark column and applied mean
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
df.loc[0:34 ,"name"]
# return all rows but only name column

In [ ]:
df.loc[0:4 ,"name"]
# return first 5 rows but only name column

In [ ]:
df.loc[10:, "name"]
# return from index 10
# dont write start and end of the range :

##How to filter data



*   Using slicing method

In [ ]:
df[df["mark"]>90]

In [ ]:
df[df["class"]=="Six"]



*   Boolean filter

In [ ]:
df["mark"] >90
#return true false

In [ ]:
df[(df["class"]=="Six") & (df["gender"]=="male")]

In [ ]:
df[(df["gender"]=="female") & (df["mark"]>=85)]

In [ ]:
df[(df["gender"]=="female") | (df["mark"]>=90)]
# | this is called pipe

In [ ]:
df.loc[df["gender"]=="male", ["name","class"]]

In [ ]:
df.groupby("gender")["mark"].max()
# Max mark for male and max mark for female students

In [39]:
df[df["class"] == "five"]["mark"].mean()

nan

In [41]:
6 - df[(df["class"] == "Six") & (df["gender"] == "male")]["mark"].mean()
#Average mark for class 'Six' and male students only

np.float64(-48.0)

## How to sort values

In [ ]:
df.sort_values(by="mark") #sort by marks

In [ ]:
df.sort_values(by="mark", ascending=False)
#sort values by mark desc order

In [ ]:
df[["name", "class", "mark"]].sort_values(by="class")

In [ ]:
df.loc[df["mark"]>50, :].sort_values(by="mark")

##Value counts

In [ ]:
## How many male and female students are there?
df["gender"].value_counts()